apiVersion: v1
kind: Service
metadata:
  name: service-management-inventory-clusterip
  labels:
    app: service-management-inventory
    env: dev
spec:
  type: ClusterIP
  ports:
  - name: service-management-inventory
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: service-management-inventory
    env: dev