apiVersion: v1
kind: Service
metadata:
  name: app-front-inventory
  labels:
    app: front-inventory
    env: dev
spec:
  type: NodePort
  selector:
    app: front-inventory
    env: dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080