apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-inventory-pv-dev
  labels:
    app: inventory
    env: dev
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/bd_inventory"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-inventory-pvc-dev
  labels:
    app: inventory
    env: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi