apiVersion: v1
kind: Service
metadata:
  name: apigateway-inventory-clusterip
  labels:
    app: apigateway-inventory
    env: dev
spec:
  type: ClusterIP
  selector:
    app: apigateway-inventory
    env: dev
  ports:
  - name: apigateway-inventory
    port: 80
    protocol: TCP
    targetPort: 8000
  