apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/"